spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: salary-service
          uri: lb://SALARY-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: salary-service
                fallbackuri: forward:/salaryFallBack
        - id: leave-service
          uri: lb://LEAVE-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: leave-service
                fallbackuri: forward:/leaveFallback
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: employee-service
                fallbackuri: forward:/employeeFallback
        - id: frond-end-service
          uri: lb://FRONT-END-SERVICE
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: front-end-service
                fallbackuri: forward:/frontendFallback
          
                

server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
