server:
  port: 9194
spring:
  h2:
    console:
      enabled: true
  application:
    name: employee-service
  cloud: 
     config: 
      discovery: 
        enabled: true


bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    
